metaphor_typebased <- metaphor_typebased %>% 
  mutate(CM_BROADER = replace(CM_BROADER, CM_BROADER %in% c("anger is (heated) fluid in a container", "anger is substance in a container") & SFRAME %in% c("fluid containment", "liquid", "mixture", "containment"), "anger is fluid in a container"),
         CM_BROADER = replace(CM_BROADER, CM_BROADER %in% c("anger is (heated) fluid in a container", "anger is substance in a container") & SFRAME %in% c("pressure in a container"), "anger is pressurised substance in a container"),
         MAP_1 = replace(MAP_1, CM_BROADER %in% c("anger is fluid in a container", "anger is pressurised substance in a container"), "anger_contents/located-entity"),
         MAP_2 = replace(MAP_2, CM_BROADER == "anger is fluid in a container" & MAP_2 == "anger-level_fluid-heat-level", "anger-level_substance-fullness-level"),
         CM_BROADER = replace(CM_BROADER, CM_BROADER == "anger is fluid in a container", "anger is substance in a container"),
         CM_BROADER = replace(CM_BROADER, CM_BROADER == "anger is (heated) fluid in a container", "anger is heated fluid in a container"),
         CM_BROADER = replace(CM_BROADER, CM_BROADER == "anger is (destructive) natural force", "anger is natural force"),
         CM_BROADER = replace(CM_BROADER, CM_BROADER == "anger is fierce (captive) animal", "anger is fierce, captive animal"),
         MAP_3 = replace(MAP_3, CM_BROADER == "anger is substance in a container" & str_detect(CITATIONS, "memuntahkan"), "angry-person_container"),
         MAP_2 = str_replace_all(MAP_2, "undersirability(?=\\-of\\-the\\-disease)", "undesirability"),
         MAP_2 = replace(MAP_2, str_detect(CM_BROADER, "pressurised") & LU == "menaikkan darah", "causing increased intensity is exerting pressure to the fluid"),
         MAP_2 = replace(MAP_2, str_detect(CM_BROADER, "pressurised") & LU == "naik spaneng", "increased anger is fluid (being caused to) rises"),
         MAP_2 = replace(MAP_2, str_detect(CM_BROADER, "pressurised") & MAP_2 == "increased anger is fluid (being caused to) rises", "increased anger is fluid (being caused to) rises (by pressure)"),
         MAP_2 = replace(MAP_2, str_detect(CM_BROADER, "pressurised") & MAP_2 == "intense anger is exploding container", "losing control over anger is explosion of container"),
         MAP_1 = replace(MAP_1, str_detect(CM_BROADER, "pressurised") & LU == "penaik darah", "angry person's body_container"),
         LU_GLOSS = replace(LU_GLOSS, LU == "naik darah", "rising blood"),
         LU_GLOSS = replace(LU_GLOSS, LU == "naik spaneng", "rising tension/voltage"),
         LU_GLOSS = replace(LU_GLOSS, LU == "pemakan bawang", "someone who gets angered easily; lit. onion eater"),
         LU_GLOSS = replace(LU_GLOSS, LU == "pembawang", "someone who gets angered easily; lit. someone having to do with onion"),
         MAP_2 = replace(MAP_2, str_detect(CM_BROADER, "heat$") & MAP_2 == "intensity-of-anger_degree-of-the-heat", "becoming-angry_being-heated-up"),
         # MAP_2 = replace(MAP_2, str_detect(CM_BROADER, "heat$") & LU %in% c("membawang", "makan bawang"), "becoming-angry_being-heated-up"),
         MAP_1 = replace(MAP_1, str_detect(CM_BROADER, "verticality$"), "anger_verticality-scale"),
         CM_BROADER = replace(CM_BROADER, LU %in% c("pemakan bawang", "makan bawang", "membawang", "pembawang"), "(cause of) anger is annoyance"),
         SFRAME = replace(SFRAME, LU %in% c("pemakan bawang", "makan bawang", "membawang", "pembawang"), "disturbance"),
         MAP_1 = replace(MAP_1, LU %in% c("pemakan bawang", "makan bawang", "membawang", "pembawang"), "cause-of-anger_annoyance/disturbance"),
         MAP_1 = replace(MAP_1, LU %in% c("pemakan bawang", "pembawang"), "angry-person_irritated-person"),
         MAP_2 = replace(MAP_2, LU %in% c("pemakan bawang", "makan bawang", "membawang", "pembawang"), NA))